version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: gait
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'

  dynamodb:
    image: amazon/dynamodb-local:latest
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath /data'
    ports:
      - '8000:8000'

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  backend:
    build: .
    command: npm run dev
    environment:
      DATABASE_URL: "postgresql://postgres:secret@postgres:5432/gait"
      AWS_REGION: "us-east-1"
      JWT_ACCESS_SECRET: "dev-access-secret"
      JWT_REFRESH_SECRET: "dev-refresh-secret"
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - dynamodb
